CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE areas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_areas" PRIMARY KEY (id)
);

CREATE TABLE product_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_product_types" PRIMARY KEY (id)
);

CREATE TABLE stations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    area_id integer NOT NULL,
    CONSTRAINT "PK_stations" PRIMARY KEY (id),
    CONSTRAINT "FK_stations_areas_area_id" FOREIGN KEY (area_id) REFERENCES areas (id) ON DELETE CASCADE
);

CREATE TABLE process_states (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    value character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    station_id integer NOT NULL,
    product_type_id integer,
    group_id uuid NOT NULL,
    CONSTRAINT "PK_process_states" PRIMARY KEY (id),
    CONSTRAINT "FK_process_states_product_types_product_type_id" FOREIGN KEY (product_type_id) REFERENCES product_types (id),
    CONSTRAINT "FK_process_states_stations_station_id" FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE
);

CREATE INDEX "IX_process_states_product_type_id" ON process_states (product_type_id);

CREATE INDEX "IX_process_states_station_id" ON process_states (station_id);

CREATE INDEX "IX_stations_area_id" ON stations (area_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250703100103_Init', '9.0.6');

CREATE TABLE control_board_data (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    data character varying(150) NOT NULL,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_control-board-data" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250709094050_addControlBoardData', '9.0.6');

ALTER TABLE control_board_data ALTER COLUMN data TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250709110213_ChangeDataTypeForAddControlBoardData', '9.0.6');

ALTER TABLE process_states DROP CONSTRAINT "FK_process_states_stations_station_id";

ALTER TABLE process_states ALTER COLUMN station_id DROP NOT NULL;

ALTER TABLE process_states ADD CONSTRAINT "FK_process_states_stations_station_id" FOREIGN KEY (station_id) REFERENCES stations (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250717101817_ProcessStatesStationIdOptional', '9.0.6');

ALTER TABLE stations ADD chart_element_id integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX "IX_stations_chart_element_id" ON stations (chart_element_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250728094056_AddedChartElementIdField', '9.0.6');

COMMIT;
