START TRANSACTION;
CREATE TABLE areas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_areas" PRIMARY KEY (id)
);

CREATE TABLE product_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_product_types" PRIMARY KEY (id)
);

CREATE TABLE stations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    area_id integer NOT NULL,
    CONSTRAINT "PK_stations" PRIMARY KEY (id),
    CONSTRAINT "FK_stations_areas_area_id" FOREIGN KEY (area_id) REFERENCES areas (id) ON DELETE CASCADE
);

CREATE TABLE process_states (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    value character varying(150) NOT NULL,
    description text,
    created timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    station_id integer NOT NULL,
    product_type_id integer,
    group_id uuid NOT NULL,
    CONSTRAINT "PK_process-states" PRIMARY KEY (id),
    CONSTRAINT "FK_process-states_product_types_product_type_id" FOREIGN KEY (product_type_id) REFERENCES product_types (id),
    CONSTRAINT "FK_process-states_stations_station_id" FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE
);

CREATE INDEX "IX_process-states_product_type_id" ON process_states (product_type_id);

CREATE INDEX "IX_process-states_station_id" ON process_states (station_id);

CREATE INDEX "IX_stations_area_id" ON stations (area_id);


COMMIT;