USE MES01
GO

DECLARE @id INT
--Заполнение справочника Areas(Участки) и Stations(Станции)
INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Сварка','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сварка 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сварка 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сварка 3','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сварка 4','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сварка 5','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сварка 6','',GETDATE(), GETDATE(),0, @id)



INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Окраска','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Ожидание маскировки','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Маскировка каркаса','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Ожидание пескоструя 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Ожидание пескоструя 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Пескоструйная обработка 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Пескоструйная обработка 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Ожидание окраски 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Ожидание окраски 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Окраска каркаса','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Буфер после окраски 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Буфер после окраски 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 3','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 4','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 5','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 6','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 7','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 8','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 9','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 10','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 11','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 12','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 13','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 14','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 15','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 16','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Герметик, пластик 17','',GETDATE(), GETDATE(),0, @id)




INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Сборка кабин','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 3','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 4','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 5','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 6','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 7','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Сборка кабин 8','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Буфер кабин 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Буфер кабин 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Проверка кабины ОТК','',GETDATE(), GETDATE(),0, @id)


INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Сборка шасси','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 3','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 4','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 5','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 6','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 7','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 8','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Окраска рамы 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Окраска рамы 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Окраска рамы 3','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Окраска рамы 4','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 9','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 10','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 11','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 12','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 13','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 14','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 15','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Шасси 16','',GETDATE(), GETDATE(),0, @id)


INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Оси','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Подсборка осей 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Подсборка осей 2','',GETDATE(), GETDATE(),0, @id)


INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Качество','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Тормозной стенд','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Настройка схождения','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Инспекция','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Аудит','',GETDATE(), GETDATE(),0, @id)

INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Ремзона','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Установка надстройки','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Участок ремонта 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Участок ремонта 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Участок ремонта 3','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Участок ремонта 4','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Ремонт окраски 1','',GETDATE(), GETDATE(),0, @id)



INSERT INTO Areas (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Автомобили на улице','',GETDATE(), GETDATE(),0)
SET @id = SCOPE_IDENTITY()
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 1','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 2','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 3','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 4','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 5','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 6','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 7','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 8','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 9','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 10','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 11','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 12','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 13','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 14','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 15','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 16','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 17','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 18','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 19','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 20','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 21','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 22','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 23','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 24','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 25','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 26','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 27','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 28','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 29','',GETDATE(), GETDATE(),0, @id)
INSERT INTO Stations (Name, Description,Created,LastUpdated, IsDeleted,AreaId) VALUES ('Улица 30','',GETDATE(), GETDATE(),0, @id)

--Заполнение справочника ProductTypes(тип кабины/шасси)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('ККН','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('ККС','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('ДКН','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('ДКС','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('ДКВ','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Шасси','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Тягач','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Борт','',GETDATE(), GETDATE(),0)
INSERT INTO ProductTypes (Name, Description, Created,LastUpdated,IsDeleted) VALUES ('Самосвал','',GETDATE(), GETDATE(),0)

